In [ ]:
# 1Bar Chart

# Create monthly sales

# months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]

# sales = [120, 150, 170, 140, 200, 230]

In [1]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np

In [2]:
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]

sales = [120, 150, 170, 140, 200, 230]

In [3]:
fig= px.bar(x= months,y= sales, title="Monthly Sales", labels={"x": "Months","y": "Sales"})
fig.show()

In [4]:
# # 2Line Chart

# Represent the same monthly sales as a line chart.

fig= px.line(x=months, y=sales, title="Monthly Sales",labels={"x":"Months","y": "Sales in $k"})
fig.show()

In [5]:
# Pie Chart

Engineering = 40

Sales = 25

Marketing = 15

HR = 10

Operations = 10

In [6]:
fig= px.pie(names=["Engineering","Sales","Marketing","HR","Operations"], values=[Engineering,Sales,Marketing,HR,Operations], title= "Department Employee")
fig.show()

In [10]:
# 4
# Scatter Plot

# Create a relationship between

# Hours studied

# Exam marks

# for at least 15 students.
hours_studied = [1, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6,6.5, 7, 8, 9, 10]
exam_marks = [35, 42, 48, 51, 55, 61, 65, 68, 72, 75,79, 82, 87, 91, 96]

fig= px.scatter(x= hours_studied, y= exam_marks, title="Exam Marks Vs Hours Studied", labels={"x": "No of hours", "y": "Exam Marks"})
fig.show()


In [12]:
# Histogram

# Generate 500 random values using NumPy and create a histogram.
data_values= np.random.randn(500)
data_values


array([ 2.80304895e-01,  7.41365577e-01, -1.02017363e-01, -1.03509399e+00,
       -8.23748590e-01, -6.83573476e-01,  6.35448404e-01, -1.21145135e+00,
       -8.52851090e-01, -8.03000734e-01, -6.01269056e-01, -8.89898033e-01,
       -1.13336419e+00,  1.91951622e-01,  7.77978194e-01, -5.46961609e-01,
        1.18227076e+00,  4.14756430e-02,  2.67828720e-01, -2.01295122e+00,
        1.92380996e-01, -5.76537849e-01, -2.50381470e-02, -2.40339335e-02,
       -1.04978884e+00, -1.25969251e+00,  1.40527919e+00,  4.34990170e-01,
       -1.43367871e+00, -1.00465454e+00, -1.47904650e+00, -7.81099789e-01,
        3.88683860e-01, -5.45046881e-01,  1.03610296e+00, -2.71332658e-02,
       -4.72511285e-01,  2.61590526e-01,  5.61354291e-01,  1.24165807e-01,
       -5.09380921e-01,  1.46109588e-01,  1.10869226e+00,  8.93990537e-01,
        6.59489583e-01,  2.19577836e+00,  3.87162390e-02, -2.44243213e+00,
       -4.16681294e-02,  1.90729865e+00,  4.01784034e-01,  1.92090805e+00,
        4.61047136e-01,  

In [18]:
fig= px.histogram(x= data_values, nbins=30)
fig.show()

In [19]:
# Box Plot

# Create salary information for 30 employees and visualize salary distribution.

salary= np.random.random_integers(5000,25000,30)
salary

C:\Users\Shivank\AppData\Local\Temp\ipykernel_24196\1809476017.py:5: DeprecationWarning: This function is deprecated. Please call randint(5000, 25000 + 1) instead
  salary= np.random.random_integers(5000,25000,30)


array([18078, 22571, 24226, 18108,  6391, 12362,  6306,  7889, 18048,
       16239, 17056, 23414, 15316,  5416, 22972, 24508, 14221, 16304,
        5701,  5260, 21925, 24923,  5917, 23950, 17308,  5142, 11042,
       16706,  7174, 18366], dtype=int32)

In [21]:
fig= px.box(x= salary, title="Salary distribution", labels={"x":"Salary"})
fig.show()

In [22]:
# Multiple Categories

# Create a chart comparing sales of

# Laptop

# Mobile

# Tablet

# # across six months

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]

laptop_sales = [150, 170, 160, 180, 200, 220]
mobile_sales = [300, 280, 320, 350, 340, 400]
tablet_sales = [90, 100, 95, 110, 130, 125]


In [24]:
fig= go.Figure(data=[
    go.Bar(x=months, y= laptop_sales, name="Laptop"),
    go.Bar(x=months, y= mobile_sales, name="Mobile"),
    go.Bar(x=months, y= tablet_sales, name="Tablet")

])

fig.update_layout(title= "Category wise sales data", xaxis_title= "Months",yaxis_title= "Sales")

fig.show()

In [25]:
# Create marks for 10 students in

# Python

# Mathematics

# Data Science

# Represent the comparison visually.

students = ["Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun", "Sai", "Reyansh", "Ayaan", "Krishna", "Ishaan"]

python_marks = [85, 62, 45, 78, 91, 55, 88, 39, 95, 70]
mathematics_marks = [72, 58, 80, 65, 90, 42, 77, 60, 85, 68]
data_science_marks = [90, 40, 55, 82, 88, 30, 95, 48, 92, 75]

fig= go.Figure(data=[
    go.Bar(x=students, y= python_marks, name="Python"),
    go.Bar(x=students, y= mathematics_marks, name="Maths"),
    go.Bar(x=students, y= data_science_marks, name="Data Science")

])

fig.update_layout(title= "Student Marks", xaxis_title= "Students",yaxis_title= "Marks")

fig.show()


In [26]:
# 3D Scatter Plot

# Create at least 30 data points containing

# Age

# Salary

# Experience

# Represent them using a Plotly 3D scatter plot.

age = [26, 47, 25, 41, 45, 50, 36, 45, 30, 47, 48, 30, 26, 29, 22, 33, 28, 41, 27, 46, 22, 56, 31, 36, 26, 31, 45, 57, 25, 30]

experience = [2, 10, 1, 11, 15, 24, 7, 11, 5, 22, 11, 3, 1, 4, 0, 5, 5, 11, 3, 21, 0, 17, 4, 8, 3, 6, 10, 19, 2, 5]

salary = [42400, 80300, 34100, 88100, 101300, 148000, 71400, 76200, 57300, 131300, 76700, 43700, 42800, 43600, 25000, 52700, 53200, 71000, 42900, 129900, 30800, 105500, 40900, 66000, 41700, 60000, 71800, 108900, 32200, 49600]

In [27]:
fig= px.scatter_3d(x=age, y= experience, z= salary, labels={"x":"Age","y": "Experience","z":"Salary"}, title= "Salary Vs Age Vs Experience")
fig.show()

In [30]:
# 11
# NumPy + Plotly

# Generate 100 random numbers using NumPy and visualize them with Plotly.

age= np.random.random_integers(1,80,100)
age

C:\Users\Shivank\AppData\Local\Temp\ipykernel_24196\382909435.py:6: DeprecationWarning: This function is deprecated. Please call randint(1, 80 + 1) instead
  age= np.random.random_integers(1,80,100)


array([16, 77, 22, 79, 79, 34, 73, 38, 63, 17, 54, 31, 44, 27, 40, 71, 77,
       44, 75,  4, 26, 17, 66, 23, 15, 47,  7, 63, 15, 30, 73, 37, 28, 26,
       21, 17, 80, 76, 25, 69,  8, 46, 69, 31, 66,  2, 46, 45, 15, 44, 39,
       58,  6, 29, 78, 80, 16, 41, 78, 26, 57, 72, 52, 62, 66, 73, 60, 68,
       62, 13, 32, 37, 57, 64, 71, 39, 56, 71, 66, 54, 63, 43, 42, 16, 25,
       58, 47, 26, 62, 60, 66, 55, 16, 60, 17, 54,  8, 62, 51, 15],
      dtype=int32)

In [31]:
fig= px.box(y= age, title= "Age Distribution", labels={"y":"Age"})
fig.show()

In [32]:
# Dashboard Thinking Challenge

# Create at least four separate charts representing a fictional company's:

# Revenue

# Expenses

# Employees

# Customers

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

revenue = [199700, 212100, 236700, 238600, 265400, 245400, 260100, 277700, 313600, 326500, 341600, 373200]

expenses = [117800, 143300, 143700, 169300, 185300, 169500, 172200, 165400, 182900, 188300, 208500, 239400]

employees = [42, 42, 45, 45, 48, 50, 50, 53, 55, 55, 58, 60]

customers = [1199, 1411, 1555, 1877, 1903, 2072, 2519, 2519, 2619, 2732, 3316, 3316]

In [ ]:
#Line chart depicting no of cusotmers every month

fig= px.line(x= months, y= customers, title= "MOnthly Customers", labels={"x": "Months", "y": "Customers"})
fig.show()

# The no of customers increases every month, and as expected they are highest in Year end to holidays

In [ ]:
#Line chart depicting no of cusotmers every month

fig= px.bar(x= months, y= employees, title= "Employee count per month", labels={"x": "Months", "y": "Employee"})
fig.show()
# We have more number of employees in Nov and Dec to handle year end pressure 

In [ ]:
fig= go.Figure(data=[
    go.Bar(x=months, y= revenue, name="Revenue"),
    go.Bar(x=months, y= expenses, name="Expenses"),
    

])

fig.update_layout(title= "Monthly Revenue and Expense data", xaxis_title= "Months",yaxis_title= "Sales in $k")

fig.show()

#We were in profit every month as montly revenue is more than expenses 

In [36]:
profit= np.array(revenue)- np.array(expenses)

fig= px.line(x=months, y= profit, title= "Monthly Profit", labels={"x": "Month", "y": "Profit"})
fig.show()